#! /usr/bin/env python

import subprocess
import argparse
import sys


def main():


	dns_server = "cs5700cdnproject.ccs.neu.edu"
	replica_servers=["ec2-52-0-73-113.compute-1.amazonaws.com","ec2-52-16-219-28.eu-west-1.compute.amazonaws.com","ec2-52-11-8-29.us-west-2.compute.amazonaws.com",
"ec2-52-8-12-101.us-west-1.compute.amazonaws.com","ec2-52-28-48-84.eu-central-1.compute.amazonaws.com","ec2-52-68-12-77.ap-northeast-1.compute.amazonaws.com",
"ec2-52-74-143-5.ap-southeast-1.compute.amazonaws.com","ec2-52-64-63-125.ap-southeast-2.compute.amazonaws.com","ec2-54-94-214-108.sa-east-1.compute.amazonaws.com"]
	
	parse = argparse.ArgumentParser(description="Deploying the CDN")
	parse.add_argument("-p", dest="port",help='high-numbered port 40000-65535',type=int)
	parse.add_argument("-o", dest="origin",help='server from which content would be fetched')
	parse.add_argument("-n", dest="name",help='cdn specific name')
	parse.add_argument("-u", dest="username",help='user who runs this script')
	parse.add_argument("-i", dest="keyfile",help='keyfile for ssh')

	arguments = parse.parse_args()
	if arguments.port is None:
		print("Please specify the port number")
		sys.exit()
	port = int(arguments.port)
	
	if arguments.origin is None:
		print("Please specify the origin server")
		sys.exit()
	origin = arguments.origin
	
	if arguments.name is None:
		print("Please specify the cdn specific name")
		sys.exit()
	name = arguments.name

	if arguments.username is None:
		print("Please specify the username")
		sys.exit()
	username = arguments.username

	if arguments.keyfile is None:
		print("Please specify the path to key file")
		sys.exit()
	keyfile = arguments.keyfile

	
	deploy_dns_servers(replica_servers,port,origin,name,username,keyfile,dns_server)
	deploy_http_servers(replica_servers,port,origin,name,username,keyfile)


def deploy_http_servers(replica_servers,port,origin,name,username,keyfile):
	
	for each_replica in replica_servers:
		copy_1 = subprocess.check_output("scp -i "+keyfile+" httpserver "+username+"@"+each_replica+":~/",shell=True) 
		ssh_1 = subprocess.check_output("ssh -i "+keyfile+" "+username+"@"+each_replica+" 'chmod 711 ~/httpserver'",shell=True)

def deploy_dns_servers(replica_servers,port,origin,name,username,keyfile,dns_server):
		
	dns_deploy = subprocess.check_output("scp -i "+keyfile+" dnsserver "+username+"@"+dns_server+":~/",shell=True)
	dns_ssh = subprocess.check_output("ssh -i "+keyfile+" "+username+"@"+dns_server+" 'chmod 711 ~/dnsserver'",shell=True) 


main()
